### ISSUE TITLE
API の環境構築

### ISSUE THREAD

**Issue by shm11C3** [shm11C3/animation-schedule-api#3]
## 概要

API の雛形作成に伴う開発環境の整備

## TODO 

- [ ] `/api` の `README` 修正
- [ ] OpenAPIの雛形作成
- [ ] dynamoose 関連の検証
- [ ] GHA 作成
- [ ] `.vscode/setting.json` の作成
- [ ] `.env.example` 追加
- [ ] monorepo 構成っぽくなっているので、`/api` をルートとした場合でも `/docs` が参照できる方法を検討する
